hash-format = "sha256"

[[files]]
file = "config/DistantHorizons.toml"
hash = "2b9fca785c882fe1379e1d45884180ca7ee9a466cc5aa9274c5ff9075a24d2c8"

[[files]]
file = "config/alexscaves-client.toml"
hash = "db5c9fddb7816fae75ecdb86e604c97408eca8626d785b9380a0b39d68b8bd58"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "a1847c3981971d2b89f16240eb34a911ec58f503ea8805711129b8313505f524"

[[files]]
file = "config/enchantinginfuser-server.toml"
hash = "2fc0a2d1331da25a185f03b2661fda8ccc398a4ec48d641de23297f9c1d31ec4"

[[files]]
file = "datapacks/curio-customization/data/curio_customization/curios/slots/back.json"
hash = "c2cf997f78a631a58da6851b690a0877694bd53f247a1226b9a4ca5dc8273d2a"

[[files]]
file = "datapacks/curio-customization/pack.mcmeta"
hash = "bc80dc435d2922d4bd66e471a00178860bb1622445cf4fec1b2136d86aa95598"

[[files]]
file = "mods/absent-by-design.pw.toml"
hash = "20e2dbcde20de2191413b7b5984425f719f957ed564ce00f69e822ac01711c78"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "dfab1141c0b00ca194d3826f3bbc06f6b50ed844ecad886bb69fb3d560090b0e"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "0cbc4b2c6b58b7a94f030ae84f18057e5dc78a17bad429f40b8884926a6ab233"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "f6cb39881349ebcd51d5ea8563110dd0fb861b66c18f7a261eabe1ef41563cd2"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/aqua-combat.pw.toml"
hash = "62fd0948a7752172b2a01008a6261c5bd0804ab3b509445589f06580b23f7601"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "221e85ab67a10bfc0de6c02ab835d9830e1d3acabc4a0c91b6629e168948b438"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/astikorcarts-redux.pw.toml"
hash = "c3daae892d91d5b36c65fbd18f19d22a61fcac210f25350cde0a413c6a49210f"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "e11ddca37c00c8cdf8ee89c7b59df544f50966d2d6c5b016916f023afb98c02e"
metafile = true

[[files]]
file = "mods/attributes.pw.toml"
hash = "f5d265ad34588a9b5d9bbba6e5f1ff02c723d7e41da8dc56124c783d90962c39"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f09f722a08e566b4165bc05005b903768cceb63e6d90cdd7758eb2a7de3986d5"
metafile = true

[[files]]
file = "mods/better-combat.pw.toml"
hash = "f2772ac30db5760b191049f87d2315f1652d9b04357e644df9d8a2bafdc269e5"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "28358fe53c22695b3bf1f93ac2225c46fe3525918b7b993ac36e68a7f0a16fe8"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "8a8ea0af79b88d9c192d208aa5be4bacd934e2b92d4721566e2e796eb9761e10"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "a613f5d2df911fea606968bbdb56eebfd05ac02ada846cf0d2e56e72345d9338"
metafile = true

[[files]]
file = "mods/cataclysmic-combat.pw.toml"
hash = "8acb63dff6a8d3ea88623ef6abf5ff6c1d17d1eaa62bb52a5a5444ff46abbd5c"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "de0ab85ea06d797c2b3b5c70c8f1fdfc1f76fb2530f792a89f4f6d9807fc649a"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "b0732421ae2999d558a7b70a11fa86a93738ca33f6f3ec343017796df9c47d9c"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0bdcf1c5057873c78db71bee196ccf5ec846f6cf82f639b094668b3ba92e151f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "e3dd03e7fec88831974857e2cdded54dd5c5bdcaa3f6d6248c2800e82db4dd41"
metafile = true

[[files]]
file = "mods/continents.pw.toml"
hash = "d6da3d9e4834b857398f1e50bcaddd5b2a47ee1be0164adc9bc8fd7be3534599"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "b2c7739b56ef71f50a86658cfa67375796beafd391c4dbe26a5de8cd92b9b685"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "97f7c75ac9bf6ee2a4f15c0f1e3e4cd161f3d2e33f32ebf623811ac90b3c2a83"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "1ad27ac63d9c939149112a6cfdddd9ef00fb9be26b1d824ba3540dbdd62e1f48"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "5cf8a06431f16a18dc468baae3fbdf17cc1d72b9697da58cb126342ed937aa59"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "e9dfcaebe165cb93ba4774f5c17bae14b5b82878593199539326f92519f59d5e"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "9c553500c771ace491481e52fb2a144e97ce332f03bc36155b62bcf5e64877ed"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "53fd334af7b7c6ada2b3d15a8d666011c5b54bcfc5515e6ca2d13eeb3c286b0d"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "a4c814876cd9046f9cdbe0a5967edff092adb8c28de2d717ce5fe469d6fbc9a2"
metafile = true

[[files]]
file = "mods/dynamic-trees-quark.pw.toml"
hash = "fa83c56be1710cf50ccff6897ba140ebd486cd4fe46870def9eed73482c440e6"
metafile = true

[[files]]
file = "mods/dynamictrees.pw.toml"
hash = "1d29f0d2a87aa2f4f0e4c1f6c25e640516fc9a43c77b5d2405a426a80d279faa"
metafile = true

[[files]]
file = "mods/dynamictreesplus.pw.toml"
hash = "dfb8c790539d6136cc757a5afebb2156d15bf66dc927c4a172d3ddaa75cef896"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "b819114773db1e86fa897907d79abf9925f05a6ae3fd10f7a02cca41f3e9a0d2"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "5789ad8bb50d419d1b8bb736137a65be4d76296575cfcd5b86997cbf5d52cff5"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "3f63f54bf638954d1da79cacc7ab2d58e1886c98bdb2b267035abfa0ce8a5a72"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "14ddf6bc740ded7825a455f90f0045ed3b4c2e65168565715daaff8532da5dbd"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ba33e2257a6e3e4ae195919d16fdb142c326261bd0ea57560820f8d9fd9e324e"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "cc4926dece87e61770569a0c558f3c2e674e036a92939afe93058d8c4263b96f"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "3136d2fa3cd097330976de6517806fb9a306b60a9c2f9f3845d1289cad11b8c4"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "ce198cf0e4ac56f35c03b5e721eacbd6c6bc86b6ab318c4c7259082edb625fc2"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "7b846273c5cbc4d0eb1f3d0eb4802b0e81e54dea84cf25666015ca50931fe307"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/flib.pw.toml"
hash = "ec9b48d07fdb821f60236006aeb33bb129abcee2ba044611a4758e31b2fa0bca"
metafile = true

[[files]]
file = "mods/geckoanimfix.pw.toml"
hash = "f78c94f42ffaf5365f45b58f83545ced3dc9ae0cf075412e7710079e163eed28"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "bfe1b9ef08ea1e5e3a49a449105d91718a74cf10628964c86897d7ae5fac20be"
metafile = true

[[files]]
file = "mods/glowing-eyes.pw.toml"
hash = "438d84e316c8221e0f3ab4bb62a1151d3c4c051c10b418a9acfe12fa8a2c4ca4"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "db495b3ac268709a2ba673bfe220b10257fb7dae549f94bfbd539617d571f131"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "dee03a68ecb0b85f8f1cae14bc759ef93116e6f0262ea84002f3921322bbf6c2"
metafile = true

[[files]]
file = "mods/idas.pw.toml"
hash = "675609a9fb0ed19788e460191f2fba6279e56e63d702c3d506e6e1a1c0c9ffb0"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2e5763fe550d18dbbad6fe65d1a008312b022fe7020c985014b36fbfa89edce8"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "0f83be0761e0014686517c20f2850242152dd7a26e87088d869028bc40a8a125"
metafile = true

[[files]]
file = "mods/integrated-api.pw.toml"
hash = "6703d5686b7249c586a3a710a909dfd0eba3e2d0c76bc152efb2c43494e5b2e1"
metafile = true

[[files]]
file = "mods/integrated-stronghold.pw.toml"
hash = "6a3e8217b2009309ea78ab26a1cbaf6ce53e154846efab841c61467426d27562"
metafile = true

[[files]]
file = "mods/integrated-villages.pw.toml"
hash = "4c370e8ae8dcd19e0cb8f59c88d054c1d7f9cb3591cbf00a7970505bc9e09480"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks-dynamic-skill-trees.pw.toml"
hash = "16d067a8f294335dcf3f4858b7285e90f4da66d081e2cf941106c97a10baef80"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "d8c354de7ab3aef949b8f8598ae57f07f1a38711d99588f27b93c1af93a14fba"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "66a8d44f5ef66075063ced8b54312a46bb8a256090d36df877b8ff58de9d16be"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "d4ce1e57da773c6157f3208eadc40d5962be2bb1d2747eae169debb6d50a543f"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "02977d28acd2089c39dbe5b65fd08e78094fb650b4afc810f757cb5cea1fbda8"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "7ea985404ee4cc9082472c6869ec146309f526e395361b39f2f4c1a43506c41d"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "b6ed220c9069f60704dbfe19fd55c976ca56ada35bcb6918c4ad226cd842b99c"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm.pw.toml"
hash = "73c8492cab4c626442dd3a45e04a30e7d75a4d42a1e48ab132b21897bb3a7762"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "bc4c7d42fd94d57b020a43dbb3aa3caaa8395c77bd872f252a8302a39b2256a9"
metafile = true

[[files]]
file = "mods/lionfish-api.pw.toml"
hash = "3e055c411c197b2103e338dc9fdcd37272df81aaf4246f801694f97feaf7d232"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "00f3f21762720f03dd0f1d60449d2a5d3a0104989223f4efa81401d94b8f3358"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "ee387ba74c2c7e999d48071408abbd1ca322e70f36e79c590a150c9572d3a9cb"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "e4f414ece2ec81f6dd2dfb8c0176670a576b988f60c8b45a1f4b749b4d008c9d"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "c671e975aad1c5aeeb6ddd19894baa899334cc266001402c1a956f83c465cc34"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "454c8dd01b9f5e9b9288f37230dd0e38b7a2bba8d14bf4adce738185626191bd"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "a205d0ab764efa4bb2eb93c114bbfde4cd3e117d117be9a941b8b56148945d0a"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "1a621ba80dc3db935afe234475501a880e11a2cc96222833803e6636154f6724"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "1191b45155fb0f23f5a3fe4b9170b73f52a1c9599de504fe922e4ea7e7e3c95f"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "27745585e7d6cebb2fcb687563ce64d67a6dedc9ba1755b34d08309f591c8e92"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "40d34a4deede6848d6a49a9f1cf8fdd2af9dd1de058ffeb77e247099e087621f"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "dd8c35f46e1998175f993fa3acfc8b17600a1c031d62e273474232299d698afa"
metafile = true

[[files]]
file = "mods/magnum-torch.pw.toml"
hash = "33ac8df50343a510256bb78c4dca99014fd4f88fdb548edd8aed6a3013f8947e"
metafile = true

[[files]]
file = "mods/memoryleakfix.pw.toml"
hash = "ade41e4315735aa9116a0222b332e03d3f8df6eea301764d40d0bdc40f5e8689"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "70bd76457fcd02b797eeaad3e88c3390b88d0e8bd15d7100631c41401953926e"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "dc906a68268eaba1a7690ddda6931e752b72aba629eec3407f252ecee76b70ea"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "370c7e913b9453b274f5beddb0a2137b7799912467fd7880a95f8fe2099f94e7"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "679fa8f3b49b9ed3fbcb29d6ccdb99bce465faa01f9cec000464ac8d4fbe134f"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "362ead0883974a7de4dd711a75ccfe71b2ceadf172211934e8cd6084977c0f49"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "4cd211200d17b109bb15f88c7b0c6ba29d9c0af6d2feb76fc7fe4eabff2e4ffe"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "e5e76b305f6e8fd611fb70695f42014c62e5f46b926d626eaf5ca0c78e394c5c"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "acaf74883794f150634fbaf000e15098162610d2e1ef2d4029a64c7b0fe71e6e"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "6ae126a7cff8e32d017433e0d443608c6c9fe1303ff5d25c0b771b6a49814193"
metafile = true

[[files]]
file = "mods/octo-lib.pw.toml"
hash = "4ee6b38fbd604374f4703b852ebe2119c6493ae09b88f6398ab256e423bd5d4a"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "f83b253ca6a8e6f2f847952704da0e1fb00e65cbb10b7c9cb15d1a1780618da0"
metafile = true

[[files]]
file = "mods/odyssey-roles.pw.toml"
hash = "7eb6d85c0116cb003c29bbfb62030d2eddfe3d219d5d8ab23a54a76ed9978595"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "d64cc6ea9645a980ef0911bc036fb217ff9447fccb0086379490cb36b76932e2"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "765987a78e5d8c782d0da2de99998b43b5907d6c41347d3804045ad109e4a586"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "4ab869d8784f4ac318b5c92fa3d9e65f997352b8b57f34b409ca6f171637f0fe"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "f79cb80b6ea599fe4ca9404465277ff7edf25118976170c28827590febfcee7a"
metafile = true

[[files]]
file = "mods/pufferfishs-unofficial-additions.pw.toml"
hash = "7dc8f1e98b0915fd6d451d09b2d696efdde9339787bf40f4665fba6f5b026fe2"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "74991cede8019cf93d1243369d840913375ab3a7d448d764c7a15f87f5bc4e52"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "8df897c0f7831e919aa528c3c1e5239f39439c123d99761230ab2357132bad98"
metafile = true

[[files]]
file = "mods/relics-mod.pw.toml"
hash = "52c0cbc95231bf52ef2a236232a14d164ada3589f7b2caaebecf523f25d11ae7"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b85e8417e797be3fdae046c487eeda8f54cdc88f3f20e462e0e229f8dd734214"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "5b92406160d9ea8a61ddf111caaecb7f6283678e2c40b08b72dce3eeaf20dc96"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/skills.pw.toml"
hash = "b0c4d5eabeff34d9687634cef9b0b4c73d27965bdafab3b1c6f903355eb7cd64"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "44307037183b08d9bffc68198280912245f8b93cf7504678eccd2ac11ca6fc0b"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "90740ea3deeebbf79372bb77df0d9830ef663f1f574a281068e01cd2295c22a7"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "4bc420f77cac5e4ededc3c1f67d937757220aa81a1c6657515d29a74af01703e"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "0be4976227df8e261fd362889bf8e85b93e224d1b1c3cd2a11b73a9de3b64083"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "906b1a08e332ab12174bc72e32b1537b7d3f0ae4a01ee7c7d50ec54dd2f057b6"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "72c0e1d4d8eb05e6c82c8959885ee5f08b8c7ede63b438e22a7422246679cc46"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
hash = "1fd9dddb35880e9262a0ef801d34058a0f77ddc21fb0e1fab0da07f692071d51"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "08a5b69474ddf223809a4e624f123dd3886362011663989c1bbacd6b5167baf0"
metafile = true

[[files]]
file = "mods/via-romana.pw.toml"
hash = "e493847ee9de43f251d5777198c92f475fc52a96d1ab40cf5a405ed40a50334f"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "c557d1b26559ef987c229187d2f2705616e78179ce04fa1c96cc3d76a1cdf1b5"
metafile = true

[[files]]
file = "mods/xaero-zoomout.pw.toml"
hash = "a41e302bd98d48062ffad14d1d021052729fc1ddff75bee00aae8110dc33bdb4"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "f39ad4c0c8eee03b9b4b9082bf47c18502159c4a987f1eff1dc04c657e23cca9"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "2bb8c65e92264ca78b851a7e04461d9ef2c1e0bfab532ece8cefed5330680653"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "f3b3d035b89519faccc4ddd8b0b4407ce96c0eb49068fe50a445d43a3baa8bea"
metafile = true

[[files]]
file = "mods/zeta.pw.toml"
hash = "4bcf74d4569def60ca031d565350952c2edcc420f26278bc7997654a77b6fb4d"
metafile = true
