hash-format = "sha256"

[[files]]
file = "README.md"
hash = "350c8137568dddb6decfc200b75efc47466062cb2fef781a2a032692409bb470"

[[files]]
file = "mods/additional-structures.pw.toml"
hash = "6031301092c6f4f74046fd6958c6cda8923f6d93c8b9551db80f7e0b10c19428"
metafile = true

[[files]]
file = "mods/advancement-plaques.pw.toml"
hash = "d01aa30f2773b3dcb3414c42f41b941becb8152a3300be6230b5593fa1c7b496"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "a0bcd01ab5add501f87cb391676a45aa096763de03f1ae28081febcc9949ac7d"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "1e876f20f5d441f1ba1fdbae58bd6c8679a9664ac41e0a4b57964530ff0205b8"
metafile = true

[[files]]
file = "mods/aquamirae.pw.toml"
hash = "f031f29be2bce2fb02e6ac50f815910b05d36137d428bd846d2b3e39c0812d54"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e06965d8aea5dee2531377f962616b4843f3af7d5bea5b213a0b257f4595af0f"
metafile = true

[[files]]
file = "mods/armor-remover.pw.toml"
hash = "3a0308dc121b78fc49f810e261fca2f63f27bbf267e24dee544f65b922acbfec"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "aa8ff6a05cb7ec70198cb696b844f5c9fdb5a7c3159352b9be35feedd76b2a19"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "2264acfbd388023f4c11b06b18e1a8b79b2b078e9fbf4cc38b31e4cb31c653dd"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "117028aee504fb12600efb5bff26e8a3ee13d472ebe7e209ee122112b98fdb8e"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "406e28c091271bccd96fb7cb2e95746ea9db1a38de6e1e2b548788f61c243d5a"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "6efd7a1efa69ba7dfa003088ba91b9735e815572ea7e465a7be07bca80f72502"
metafile = true

[[files]]
file = "mods/biomesyougo.pw.toml"
hash = "0ba03334053447703ef0bd73fd19fa6d3a3ca7bab0b0a193cc397a603de8acb0"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "f30dc5b64b12df077cabf15d38ad1480f5459a8025de2d7ee71232d1dcaf383a"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "3369ccf13cbc0d0b3ca896002a55c64f56fe4903868cce9156a6dad22e99a46c"
metafile = true

[[files]]
file = "mods/brrp.pw.toml"
hash = "237adf3d222f54a4ccd1794c57b65ce4961212977433f965f8069ee9dba35612"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "1d51fa0d3f0ca14c66f425643120f147d5eec29d48c5ac595351db20cdf9ee75"
metafile = true

[[files]]
file = "mods/canary.pw.toml"
hash = "4dfc7f17216c5fde916187e5ff1bb8688fa2f6ae7e6f40891823db7a8675d196"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "6b13420e812b4e9307fb162490f7624e9167daa04073d16d1140e851fe70841b"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "d42a44515e657e67431cb042727db14f697b6d80c88c1da5fbe4c8afce738d29"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "36b059a08858d8a67c051da3ef5dbaf71787482156521c37c8284a36230e6bcd"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "fe2b1cb8e815ed0fb5fbc46cb808411237f1694dce52f87242a1798fffcfc558"
metafile = true

[[files]]
file = "mods/connected-glass.pw.toml"
hash = "e52dc7cdbcf6c54813e18c09780822f4be775d8b80e4a39417b48661032c40b7"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
hash = "2015d20f522326afdb9005e3aeede79ea9ffaf5b3072274ae14c077943b62033"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "7342959eb86faf584e6d64417064dd793ae6b4667f51954f4169d11fe5f0d5da"
metafile = true

[[files]]
file = "mods/corgilib.pw.toml"
hash = "1052dacc31da664492ac60677ba33f4f4402592b6897908b700000f68c04f176"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "40140ae685c9841d892eb2be0cd70b8c48ae121d99808bc293ab4fbdbf879c80"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "8db857d646fa9bc201fc1f2747d82ab8bbb69b98fa1d79a4d88fe0800071758e"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "73b933d38189720dbdbfd1f2f1a83231fd99d844a217fb90408809ac7a12445b"
metafile = true

[[files]]
file = "mods/create-structures.pw.toml"
hash = "e427c13317e4be2a5e404a732282c3df15d1cd3c2db37a8e56b5026cbb98ab70"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "8f7b16bd319a4c534acbc80f83e4359b756b301c76444d5a0afa1d1cb45d20a4"
metafile = true

[[files]]
file = "mods/ct-overhaul-village.pw.toml"
hash = "2104479f2534504ccbcd9d815d22d1e69bfdfdbdf6d85192f3570978bf11b239"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "6ebb19de1a5ce8a7d2862bfb892d8dd77efd08df9209c6e942c05e560ea98b9c"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "85c48053799956d7c0a905d6d44c64991b8564467efe7bdf053deb9dca20f7ac"
metafile = true

[[files]]
file = "mods/easy-anvils.pw.toml"
hash = "98cd4ec5c05f16d6440520cab6780d4fdc9d78b7a5f0d6e4146aa38cc88d3c5e"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "1bfc59cceb5c333b45f06ba231b3ca7ba1ed80354f9e685f73fa7f3174b2f712"
metafile = true

[[files]]
file = "mods/embeddiumplus.pw.toml"
hash = "52a5d63f5461d9335b057176a27a40db038bc107dc818b5829695960ee2f4430"
metafile = true

[[files]]
file = "mods/enchanting-infuser.pw.toml"
hash = "bb326d03345b6d50bd5f854a8094ceebb9bd6d85328788db12e5694cf1117e1a"
metafile = true

[[files]]
file = "mods/enderman-overhaul.pw.toml"
hash = "87c292d800300032816b0478435b1361752f19c401af9084d87c97f17fe25267"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "fd53dee2e2a1fc2d29aead59eaf0c86f85f620056b6e8b5bdb853e9f16ea307c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ea0d8c35669646b8d739a20b97a28c48744dcdea889ccc3c39ccd1431bf5cc6c"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "49d85ef3ee61d410392779cf4d5d430055e862e31ef0005709c0edcbc45e3b07"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "5d31747b69a3c0fc9ac7971020ca2a2247619a422ffcf4d7a5f2b6f650ec1aa1"
metafile = true

[[files]]
file = "mods/extshape.pw.toml"
hash = "f262baf9d756b0091bbeccf37ec91d7475da7337e7a6955f2a13d789b1c533b6"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "43f19afbb308bff77774f842401b2b68cf60252f9e65091686a0c90634e6679a"
metafile = true

[[files]]
file = "mods/fastload.pw.toml"
hash = "ab6d5c5981eb90445718e5224c7e92a04e4f180373b11fc944d7dce43c704318"
metafile = true

[[files]]
file = "mods/fishermens-trap.pw.toml"
hash = "9742b6a045a1a7662b9892d0253babc0b390928aa101c9271ab1780825779514"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "c9ef346647b6d4ed7417f27768461cae6496449b74258b6d81c560e95259c9dd"
metafile = true

[[files]]
file = "mods/galosphere.pw.toml"
hash = "7aedf0a040f4320ac3e97634819992259a8aa78f714fa7f7c4ca7ae982afb140"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "cf303e609b0beaf097122eecfa869d21be642e22465021f4f5aa0fa38c72b119"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "f4472b39e794d2c687042eb9795dcdb6bc7d3c88620e2e38cfa6e4983fa7767b"
metafile = true

[[files]]
file = "mods/ice-and-fire-dragons.pw.toml"
hash = "593b0f730992c1cd0f9b5352219180becda1a994cd8d8f0da1bc1611dde3afd2"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "655ca0b2bf050048f45312ad2ac15ce2eec09455b8902412907eab3a491bb31f"
metafile = true

[[files]]
file = "mods/idas.pw.toml"
hash = "c5cc662513953a95db0fc0c8d98186d1f1100478683520ed112f2cae64ea84e6"
metafile = true

[[files]]
file = "mods/immersive-armors.pw.toml"
hash = "30e1086c8c1e9b3c09b5b8031f9497802ff1220ac5e522eec151465a0fdba5af"
metafile = true

[[files]]
file = "mods/incendium.pw.toml"
hash = "38277c071e79128e516e6f83322775dfd2324a21c4812453e02067b23e3f3b09"
metafile = true

[[files]]
file = "mods/integrated-api.pw.toml"
hash = "f982446e0d81644ee7ae042c7014ce7383d625850b7f17e288768684c9bdcf70"
metafile = true

[[files]]
file = "mods/integrated-stronghold.pw.toml"
hash = "08b87444b18f6dcfe664c0acc308c30066c7ca3b2ae8324e1c86eab690c5860a"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "85e7756653583905111de26490cb243115a597b663ec4cd2bd5514dadf1ead0f"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "77197d1980dbae42a4bd5dce2cc5c162c9487e46178e3a528bb82fb136c18243"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "6fbf022fda5e7b0715b1a8729ecc9a09121f63244ba3a0f20da97741d3c9195e"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "163ad35c484056b1f5f453c7e4cb8506b325d5ec6875d8bb7086dd5c75f9acf2"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "aa241e1683fe80eee9cb233d2a1685e4ee771f85723db9861c168be584d60c60"
metafile = true

[[files]]
file = "mods/l_enders-cataclysm(cataclysm).pw.toml"
hash = "5063cd9a0d1f9ff4ab1a2a19a6c52467c0d176b4ec61c86efbe57c046da421d0"
metafile = true

[[files]]
file = "mods/legendary-tooltips.pw.toml"
hash = "a2961c6134993521eda1a60ca4de659d68ba898d774b42b3c992311999f41424"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "61da9408e9e0dfd7e6e8aeeafa90f4d8e56c95f02a142b1ccbee3abe7cc2cf5e"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "09937a94bda8971fa8b0a4cbebcf8368d67dc342fc668c880e04307c24c1833a"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "87a1c8b418ff76f239044cbf25309727318f6f9b6bd3e7ab0693798a5c261fe6"
metafile = true

[[files]]
file = "mods/minecraft-comes-alive-reborn.pw.toml"
hash = "246a888eaf8c8fbeb02dd7b7d5ea6cfc0e6ef38d955602ea8e8c48cd1e300d08"
metafile = true

[[files]]
file = "mods/mmmmmmmmmmmm.pw.toml"
hash = "512c34cf75ee99714b732ed330b1b67308480106dfd69185b3e09d42c6aa0d29"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "a9bac232dd82ebf6741c23c52bf73eba7396e9c014d47174af3e07379417d7f1"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "9cba22bdbc8c89d44438b1e22ae677f7d6bf1c7f1adecfff2760427f2d974dee"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "01a057038ff0001c216ed30504059aa681151010aa9b2810214e166de1da61a8"
metafile = true

[[files]]
file = "mods/nullscape.pw.toml"
hash = "eb9e018bcea14732b53ca4678593c1e9f7bab63cc11f8bba497475bf975c20be"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "73389d33df0e78425c139ae64f2b1b8cfa2dd2e9503c53f5eb47482f7191c722"
metafile = true

[[files]]
file = "mods/obscure-api.pw.toml"
hash = "eb33e2c8ec06d4242a1fc4bd3c7176754274d3a271d601f853179e75ac134d69"
metafile = true

[[files]]
file = "mods/oculus.pw.toml"
hash = "5e3c1bece72d73338583e26b5018819b10eada276ebc07af41d1417f7f8d8d0e"
metafile = true

[[files]]
file = "mods/platforms.pw.toml"
hash = "7b6af85f9b4e6c4e7d05cd8ad72da3978f70cc79d9d75eb59834e9beb3157b94"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "d6c0f05a4982b73b78910bd95f917bb8a934f4f233d218a3ccc22ea7ecc8bf55"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "acf3d6451ac44c6ae1c17f50b65eb8495ed24f851f818f45346a15d93696f611"
metafile = true

[[files]]
file = "mods/prism-lib.pw.toml"
hash = "4bf65f31e942662ad357d0f0dca6c1c8a9d109079e01f5ba6eb18e90f1e92b0d"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "827b361fcddfa0bdb84bfa0ebf0e1a38b139804c92aaf9e39218d784e4111fb4"
metafile = true

[[files]]
file = "mods/quark-oddities.pw.toml"
hash = "90560337b2ad996abe8d1fb74130972b83ff9954d1742bbcc1a8588aa5628528"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "c683cb91014392a4478573dcb54a22a64fdae1c04f998cd95b2e39bf313bdf1d"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "02a4e039263330615ed6d5a7afb142c9df78f6dad431e05f13ebd329f4acef83"
metafile = true

[[files]]
file = "mods/regions-unexplored.pw.toml"
hash = "d24de70bbcd2460ebdd4ea16b88f7aac305f7f6fe3b306e00a8c9f79c6c2c611"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b551987417640fee1dd523b43db90757bbc0377be7638fff3b0d76a6b7785c93"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "7089cdcaf2c1f1b9f6a9a28195c6925cda1af4dce16fd9f6f241d6340d5c8911"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "d6fdf1eba1fdeb8cd6c91778429248fd0f227ae8cf9b38abe282084f5e471e46"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "395187b6dffe299b4491e9a71109b9bed1261426ea1cabadc8679ebb6c4b0388"
metafile = true

[[files]]
file = "mods/shetiphiancore.pw.toml"
hash = "c099922d35787f4e8ec9f687fcae211b072975e5c1ccbf984544f529d45a70c9"
metafile = true

[[files]]
file = "mods/simple-weapons-for-better-combat.pw.toml"
hash = "4287e003d462529cc72b80fad661432061adf58c5f9761e77bbca56ef7a1cceb"
metafile = true

[[files]]
file = "mods/simply-swords.pw.toml"
hash = "d809063e047a9dd1e02e18ec6ec4d95864c13bc55f83de03ceea6a7f112ebbac"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "51d49c8247e5fdbfbc1c103b7c6f36a4412914174f9b225f08740ba9613ac7b1"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "d42a4342778c40d0f1ba9cc3a31ed4834bbaf6dc93aa94f5606f9cad106db1c9"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "61799bc6367ee86a72fe54b131576cbbc6f4dbe1a1a134d561e83b02a72691be"
metafile = true

[[files]]
file = "mods/spawn-animations.pw.toml"
hash = "61e88480a7df95b00cae33f2dec5eadadd96ba4d68e2536ca036584495961a4f"
metafile = true

[[files]]
file = "mods/starlight-forge.pw.toml"
hash = "f8f7cbc0daf05063e9d314d9492a87b2484d97e812a418d9a07b9099bb664021"
metafile = true

[[files]]
file = "mods/stoneworks.pw.toml"
hash = "fa859006d662af858ecc1466fb84709e1e888f9fa83287b9efa4a21dee9b06c7"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "398222d52f12efff3677e283566822a2766a68d98267261c916eda974a899c27"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "0bd8c291f5e00f334f49cd0dbbfa96af803a1f5da844003aafd7829d814974a5"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3836a80bc2aa269d72d864eb0d3a23b664e9c52c6b17d9883d10788bd5b3b624"
metafile = true

[[files]]
file = "mods/tectonic.pw.toml"
hash = "ff98fd7419e9444b4d8affb1851f51de78262da256578fd93dd48c77e15bfa39"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "c0e3742de5b13c1526799649510b7f573bb4bb340527df9eb21579fc71a4605d"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "970bd250c0bbd6ce0249c6e5bde09adabda4969e13ead743f684549b31beaace"
metafile = true

[[files]]
file = "mods/textrues-embeddium-options.pw.toml"
hash = "499d3c92a35266a11112df08d5c728b01d67051771a777f0bfbf4b92a73173f9"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
hash = "2033724e9709c1ccb35bbf7a116d5a9eac04c5267865a2dbeea89bab3a2ffbe8"
metafile = true

[[files]]
file = "mods/tool-stats.pw.toml"
hash = "aa93ac55cf1b3ef184d88151bd9d44e2c46d6c5848597a81e24dd9b332cd57f3"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "d1581564341c5d9e3a837e0a1af73bda0a297c25043fe57326a6f5199d5c0a97"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "3f285efd86db37d6f60ecf1c1a8513d86197e189d6e0eb71fa0484f09d61cc86"
metafile = true

[[files]]
file = "mods/upgrade-aquatic.pw.toml"
hash = "4af196b775f5a6dd0856428384e1cf881ed6145c12d137d48b560caefed92a2c"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "45951d2101d05815db6dec9940bff29ab8429d98e74d53d72cf2c7a61c360668"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "69305dd5539decb11f0dcd0056b959a9fd6428121bd945b27e7b181e63f6aa52"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "463f2e66a9e10603de7652413cd2acf27ecf463261a15b920bc5a90d1533baa0"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "2fae3490a06292d2ef7e8a6125e46d9f783d4f638195b36a972a8a328c00abf8"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "b61abb40b16c046f95274f3012761aa2137401a8418fe6d0267ea912ea273a2a"
metafile = true

[[files]]
file = "mods/yungs-better-desert-temples.pw.toml"
hash = "d88fa4abff459c360b6261b81bbaa59297a38c0d8518b4c7bd53b8c65df1320f"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "1ac58d356d4a274343f83dde04f6c537bdbd06ebb09c0d020753be17478f30bb"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "a3a3e8a45c0e33773efe3f29d6cadbef39576b01ab1eac4397eaafbe9d50c612"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "edc2a536158f0a5feeb9823ee45c9217445bf8eb59516d3f13f26d5b114a507a"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "074c4c4e8c671b0ebb615f18de2f9d91b35668b4a9b64f50010d25569ead5001"
metafile = true

[[files]]
file = "ops.enc"
hash = "0b826208a02b1c8d1ad9219eddaa869ff3881ac4e35b69d541483b4391294dcf"

[[files]]
file = "resourcepacks/3d-crops.pw.toml"
hash = "ca813dd20d49bff1aad639a671da5b4bfdf1cb5e40de13d5e9c0ddc9754c3dcf"
metafile = true

[[files]]
file = "resourcepacks/eclectic-trove-legendary-tooltips.pw.toml"
hash = "f88e09f4ad5f541b2dcec7326a67769286caa4e2b339cf388f151111656d6f74"
metafile = true

[[files]]
file = "resourcepacks/fresh-animations.pw.toml"
hash = "7878f5d233c73d9e22d54c7765e68b9227103ae88cb5c1e8bf1c99d2505d8f9e"
metafile = true

[[files]]
file = "resourcepacks/vanilla-tweaks.pw.toml"
hash = "d8f295521030461ebbd0e6d9541260cd9935711c78f2cad9a78edc95aa4b2c60"
metafile = true

[[files]]
file = "shaderpacks/bsl-shaders.pw.toml"
hash = "107b8b43e9fdd45cc38780875db8e4b976fadacc261f45cb39addd4e0ddb576a"
metafile = true

[[files]]
file = "shaderpacks/complementary-reimagined.pw.toml"
hash = "1e9f9f7053c256baf766dddba7a1f929634f5629c6787ae4ff1f117159232c22"
metafile = true
