hash-format = "sha256"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "29ee18f6cc9ff4948029892820bd83dd645580691e79bae2192711d54bc38e89"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "be86dd96391b15bb2df56997f848c901d3a9b1e844974bd5001a76c7262a578b"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "401e6f8ea3922a0fc69dd8fd126280133fa4e94e7f6558ad916bdef0d6e68bdd"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "5724ca10bd6d37de46834ab762a46f9ce09175f0a4fa0e2ab633846067940c03"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "958505547fc996ec4a4173743280a4878776fff7621f4b86becf390c29cb0588"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "c9aca350959a8936b054c7164fb55d789ab1e0d38cff2af48b78f70af2bc0c6d"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "992b0dca9683f225fc774d779762d18a009f2d82b9d051e7c0b55a33a95d9238"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "8fde54624913d86f1176cd1086fa485f1a872573dac144347c57cab76596b715"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
hash = "00a6a59105f7bc307cf04c1dfb129b300c29a4cb550a5825cacdb54dbc598c68"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "9a31384e891fd38ae4cdc606612eb6017cdc436cef194c22e58c36d8c942db90"
metafile = true

[[files]]
file = "mods/common-network.pw.toml"
hash = "8831fd4db9c71c69f67d53b54e9c7d2c30b0c05fc486b0c7ed9a7d3330ce0826"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "a4f671d5effbe2f3c01e4c8592c4e0818902343f7783a22f32da00517235316a"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "e7ab61139edaca7ebf16131d8292a257e45b3dc1b027234ce2b4f0f27f850004"
metafile = true

[[files]]
file = "mods/coroutil.pw.toml"
hash = "d901f874a1e09747b8d0d072c38c426eceead1f29c8ba36680f8f0082996b152"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "699cacace84b427ebcd0766af90c39e8396e9fecd03821558658041cb93e09aa"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "2b7e219bada386ccaef89cfc13e67a0f8420728d73bfb8519f27b8c96615182b"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
hash = "cd4c4ec6ef26d2b61e0cb0bdd398e8d528b88ebf739fc0898bc8cb2f7a88debb"
metafile = true

[[files]]
file = "mods/curios-continuation.pw.toml"
hash = "237a52e17edfb00eb82851640f45fadfa4faefd99c3dec98628f013fe41a1dc5"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "ebbad87beaa49c048b8374b497f83233d6e01630e2d525d6db642e0137b63fcb"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
hash = "fe88386ca7a7c34be094f10e3a012810cec23f21b580dbc1c908cf95a17bf6f8"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "1c57dff8f8e04e0e6995a888e62331814853a18942365c2b47b4776e2551fee9"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "4e6cce2a40f56a58a5dffa924b05a27b7cc618c4c9afd611e5a2ff247a5a1065"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "78e6623084bd14f68ef1335ae8a419238c4119188b90fd9e71faf45c4f049942"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "9dd64e441574c745b5d6b8f396dd266f91ac7f54dbe4790d45551f18ed13533f"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "867a029a8bed75bea2fb02e5186730db46ec01f970d0bdb266c6897074c16177"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "54943bb78f42b06ae8312e0cb4b1e97492e5e1407500d8495149f5b40205bda5"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "97df06d07cba2990d9b252fb7ef701f5f57b3473fe5ade2b10f39829bb0e3f34"
metafile = true

[[files]]
file = "mods/icarus.pw.toml"
hash = "19e2d53f4bd7abed2be25edd3af43113a281344fa2a4fc3d5326f3902f7ba9b8"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "cf8b70a9aee53147acfa4f6dd545baf2a65a597dd456f04c65e8ce378afea11c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "4c6d9e09a9cb4dbd1cae6a962da9a5838eab21a3cf8514784359d6ae0dc13199"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c3c06a4839ecfd4717686f7394396a4fc66b7a2e8eabbdd51f23ab2a1099cc1e"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "9163b758163681f75e2048c798be880c50392684b127d7d87f42ea588deceb62"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "3272f1c8e94191a33400bf0b790bf50a3cac71b6029db3344ddcf9cc5a85631b"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "298501d10980ed74135b92bb0ce3aea2008094c682176cdcf9e6274c03690407"
metafile = true

[[files]]
file = "mods/jamlib.pw.toml"
hash = "ce3a430c123ff460df270c3387820330819cf31fef5ed3cfb0411f82c0357e82"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "77b86ca843207273549875640b1c16254c2486e67127c37344c186b503da96ed"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "250a60ad345454a739a4ed90779501c31c90f5be387c3e52816ced6713012e98"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
hash = "f25c3a4dc17c8893f4f69dac220e1b98a8603e5e8b30ca29c9a70e269b343663"
metafile = true

[[files]]
file = "mods/littletiles.pw.toml"
hash = "1b5c8b3871a1a611ad25e4b3aa74636a6d5733f0d32d95ddda68e75b1a1b7a40"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "0466135afa02cfcbd7447eda8f38e708f3d01a56719a3526b696a2d672b4ad87"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "702df8b679041c5f459da5a0dc456f70de336810bc69ff726d8c925bf484e99c"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "035f96d7dea40cd3f44ef884c3b214904d8892a9b44c48d679b4317cefcb2422"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "238dde67a84fb867a6dfde2118d36371cb85420b3ac638976aa32899195af11a"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "734da85a1770ed0489132d97ce86130c5dc1ae1800d5802d5ecb07f44e15468b"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "0d0343d84ff11294b674d44c45d28281272ffa23d96f2edc368317747aebce03"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "6bc414cc0f2d4c078fe83f384d786343f701f371d657c5279b5b0df1595804bd"
metafile = true

[[files]]
file = "mods/musket-mod.pw.toml"
hash = "359f98f5d3028b8f9383258479cd2852054ad3475e18621b63b50864ff5852eb"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "abfc8909de1c851ccf4ef296e05d1017332a21fef76fd1f938828fcff925115b"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "3369ef3b2d68c6e54827e38e27d749444765b8da9be3202dc1139bba7f16a70b"
metafile = true

[[files]]
file = "mods/open-parties-and-claims.pw.toml"
hash = "5c576ee00b07cafe6a2eb04b84d89a5cc61ee21a6e66cb81522ab5970f8a7229"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "225fad05428589bf0efe18c3540a9103eaf3280fa15ad1293ef04efa3318b14f"
metafile = true

[[files]]
file = "mods/polytone.pw.toml"
hash = "02e69b2a3bf9b5fea347b6a6c57cf973d599d1901dfd596c820a059923fd377c"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b954467adc6c354b2f56390a2d993f1c6815e5032ba264cd2b59c08685d4fb60"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "53b7873e229f9ffd722c84a3e277af26e10ed774d59f459c6e052db771c9620b"
metafile = true

[[files]]
file = "mods/rightclickharvest.pw.toml"
hash = "899258d7a3b8470e4152dd07c6047bd7e507af41ff2cdec4e6ab67caf18e78ea"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
hash = "e131d7b3a29159bc9d2d421b5bd87811569a5ec55becceadf71e740866edb4b2"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "347cac2ed12c9bc0561b6a59eeb4c121b10e5f3f71d54e9bf8d1343af57ef5b8"
metafile = true

[[files]]
file = "mods/sooty-chimneys.pw.toml"
hash = "10f083cb73522f85438e6b72e8602b0f8a747ebbb9f1a69542a97edd08c147ca"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "55dd892aa92eee1c15e2d6d7832fe36226548b181e8424130f320fb9668c0514"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "69288db622d6d7d89c732327c76aa697d4aa13137353dfd86bca9ff0406ce201"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "1bfb26729d5a6e7a25a04c31df23529193e983fbaf730eb9011175d66b823325"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "593fa7b30ab016aa45be07bd6bef3a9f160ed0f24689850d60bf84995d69b843"
metafile = true

[[files]]
file = "mods/sparkweave.pw.toml"
hash = "fbbd0509d70c5cec051a64927ce085e1529e7a280fad8ee2659163fffadd16e7"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "7098bc36dd1c26d0077d34b75497b223e0d0889b5beb8c93259b3ab8b2cd7133"
metafile = true

[[files]]
file = "mods/what-are-they-up-to.pw.toml"
hash = "25c196d1706a86c766d5868f8d8d4b53dfefdde3b5b6165c5c5297a7560e412e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "943c497e1f537129a6eaaed1886f89043f0c06753e199abe890c5385ba026069"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "30e1fceff4fd5d769c044f2f8775656a641bf71993f3246d7965712bf2706afa"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "9de861902c7a3f7cc88f51a920bbf93be84f2beca2206073eb511a2963d37914"
metafile = true
