hash-format = "sha256"

[[files]]
file = "config/defaultoptions/keybindings.txt"
hash = "f875a7b50dea72661141b712442a9adbe3ff17ce7acc0e80d1f5172e7774f94e"

[[files]]
file = "config/defaultoptions/options.txt"
hash = "361e355e701f446ce81d596985221687f7fe37f30c504c7dce547a1e6f7d5f86"

[[files]]
file = "mods/ae2.pw.toml"
hash = "b4160f327578ee994907c217b8de09e2c4377b5735b12ad56d91cb1a08ddd62d"
metafile = true

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "62611a2b798035390a280b158563cfa590ab6f3465b77be46949839809dbe77f"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "92a2077fb3d27df20550d579d14c43b1feaa605796b217efb7a9d4bdd727f3bf"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "5724ca10bd6d37de46834ab762a46f9ce09175f0a4fa0e2ab633846067940c03"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "3b54c67c1da77c1228c3e29d07ac323c033cdfb348cd8a3980866cf638ac476c"
metafile = true

[[files]]
file = "mods/applied-experienced.pw.toml"
hash = "48a2d0afca1ac1a40ab7dcf84172e100c06942709b6199148e5ce6729f7ec7c7"
metafile = true

[[files]]
file = "mods/appliede.pw.toml"
hash = "f74a04997c8c67f67d732aa7d6d16f23eff8f8db72bf1fb3f59278b4f8b9f0dd"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "6d3a1c92eee4dd671253c41ec000ae48064a33c45263d6adce5cad466395169d"
metafile = true

[[files]]
file = "mods/ars-additions.pw.toml"
hash = "2643451cedf7ca89ba11bb6e8c62a72b9a4d94652f21cf0ce96fe8f7644caf59"
metafile = true

[[files]]
file = "mods/ars-elemental.pw.toml"
hash = "ecc99c14cbb3fb7fa5e57d331d5827797fd43a3233ead28dc3533b6474b4628a"
metafile = true

[[files]]
file = "mods/ars-energistique.pw.toml"
hash = "8ad679c28c8d8ebf85609b571b4556bfd9f605506efbaa6907a3045c965ce8b8"
metafile = true

[[files]]
file = "mods/ars-nouveau.pw.toml"
hash = "4b021bc7a0881ecff8ed03d2b8b0b14446d7b5837300d0e56198d2189db357bf"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie.pw.toml"
hash = "cd8e134bf9e4a82fe28fb045e1f4a78727fbc39fc3f5bfe71bba899dc44a1f63"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "146dd7165c696bfa10cd8e6fa90dd5b2578244ecd35e041557b76b0cff2d0fa6"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "e1f1588b18947699ddc9b4f7c5b5406c5559155b8cb52dcd0f203c07c31cd0b8"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "307b5f118213f204bdb39079b734d8a8027edb1a090007ce82e6403132aebdd1"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "b8446771b0d1d228cbc3034ef75e81e4e07627c74368624664acdf4daa9fbfba"
metafile = true

[[files]]
file = "mods/cerbons-api.pw.toml"
hash = "479dab388743fb59d3399d2d87a0a7dc0819a4184b74f734fa9cc1eecdd6f6f6"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "11e90b6ebd7a0900e396f9e713ce9f0fb2ec8831bf1e0183ee2f7b145f6388a0"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "24c6c3fe917ffbcef04e788dec3e003d0ed03433bc00f9cf4f23fe9b85636aa7"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "1d5cc2b6dcfd1fc3adba4566b1c29b57ff1175316678c1f22e63cbc3e28a5ba0"
metafile = true

[[files]]
file = "mods/chunkyborder.pw.toml"
hash = "cbb43eea425a91c64af48e3275d190c630300a735fb3696b35aadcefabf6a570"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/cobblemon-box-link.pw.toml"
hash = "bd507376d642397a91270f81e2107a0100a1124f001e96c8ff3a9fb47ed4e82c"
metafile = true

[[files]]
file = "mods/cobblemon-integrations.pw.toml"
hash = "69c59f5d7eaf9489c5e0f870e2b5bf1d5c5e9cd8dbff028f85dad5896b4cd09f"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "4a00a23c01074bdc034b050d1da6eb2369c3ae12642f795aacddb00ffd365206"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "e3cb1eb238192071af93f764e3ff2c493f4f437802bb56273f664bafdea13f1d"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "97fc734f4cae192b1098173966dcaf66e8e65c0f25d3fb3a57031384927250e8"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "9f920c5f1df2577cf374285e4aad4f2982a30ea2a3da1cf7ddaf25e04b3a2e31"
metafile = true

[[files]]
file = "mods/controlify.pw.toml"
hash = "ff49f63906cc95a7122324667d060947c28a0ce5cd6df9ca0428c7326945df5f"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "65c8086d2ec3d39acc7bd36c7a0306ccc43b602b38fa07d13291bc478ef7dfff"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "6f6ecb72aa956a4461add613a717d751879092c6ef30bf1e4c8576e165324da6"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "7053f05ff01bd873d3df5eeecdf303498027bcb3ea1850cffacba0c9b801e9a5"
metafile = true

[[files]]
file = "mods/create-dragons-plus.pw.toml"
hash = "a003f242af42201fc9ff0df93004424bca32955e3bb870a302ea585f83fcc657"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "c98af4e7fe5cae8719bda03923e1c517dc52f1ea8b5d6e8d6e58c9d2478ff29c"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "a4c8371232d9f542b180c7bd7e30d84b9e958b97b24af5dde0759ab8e511fb8e"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "bffb086ccb18831669912bfca626b405a180555c3e395301089d3104336dbba8"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "f92e7a06645e41ea1934dc420eb2772edb1708c0d71cb427baef8cf753acb934"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "1d99ac75f92996ec9673e39c012a51dc4b05c48ef7bf672ccaf5e7464a1a3d13"
metafile = true

[[files]]
file = "mods/dismount-entity.pw.toml"
hash = "b725bd96844d15a5e9017ab0ac09154014206c6918ebc3b83dcdbe0726a05bc1"
metafile = true

[[files]]
file = "mods/domum-ornamentum.pw.toml"
hash = "757d82d85e87524e67e5f86a0e662b1b1263846d73d98f4da098730ee499ecdf"
metafile = true

[[files]]
file = "mods/dynamic-fps.pw.toml"
hash = "116b6f924be2482528244f99447ea8a53ebcae60ffc46551f301378e58487797"
metafile = true

[[files]]
file = "mods/dynamic-lights.pw.toml"
hash = "ea969a2c6d77b5e7c8bd8ab8fe52c0c46de676a9cc517f014965699d90c5ed92"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "4e6cce2a40f56a58a5dffa924b05a27b7cc618c4c9afd611e5a2ff247a5a1065"
metafile = true

[[files]]
file = "mods/effortless.pw.toml"
hash = "fb15c2081315f5d57a085056246f0f2c221e318bb81564ca631220fea650bb35"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "467d7d44e4da1ac78b4c80b71ddf8b91cbca4bca068318f6ee548299eef28e82"
metafile = true

[[files]]
file = "mods/enhanced-attack-indicator.pw.toml"
hash = "5fd6cb9f5052b6b7891f2a4ab8c874f125a263a4b03cad5a3b2b3f80c57abc6a"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "ee7f8452c2c1a9f5a4d67fb44e69c9ec0d18725ac383af40afbbc1d1157407c2"
metafile = true

[[files]]
file = "mods/experiencelib.pw.toml"
hash = "f3f4c84a0618e7559226a82b23bdb1ece40d3d03bda4f84e57db4db6b0b42cb0"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "fb1bcc04027840cc3f8098d499c37dbd0e37f5e6f0d0981eeb7a344199fd9a48"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
hash = "ad8209e472d463c9fcd19ca708fcd9c1a4a1bc69c9f0ca22efeacb414e9ab7a8"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "cb56550a957dd44cab4f9102aa588cd22421cd6b4099a03ac7b1b167c23c0f13"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "159ff6f2ccc1c41ef2f615c804ba8b04aa27c8273ef1845a66bc7a40fdad88e5"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.pw.toml"
hash = "c20d5829bd3005c16da7b40495524223178f5f204cdc5ca05cb40c3246aec95d"
metafile = true

[[files]]
file = "mods/ftb-library-forge.pw.toml"
hash = "a4f2d610c81a2696b9a4a2ef9c569ec2caf1dd615c78fd70f73f91ad3a849c2a"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.pw.toml"
hash = "38d1ce888e383fb1bd1d3648d0ee26b643a697d3ac91e7fdb144cad3f9f55748"
metafile = true

[[files]]
file = "mods/ftb-ultimine-forge.pw.toml"
hash = "3820c5e6b19737c8440ed1f599367299694045abac139e3dfbed54ba0dd858ae"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
hash = "d88788a00e76a1c7489776cddff1e9179676e842a7cd9f04b59ebc9b3e40c7ac"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "629b53312afe295222bc721338a3189844157971767e377316492068c453abf4"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "3d0defaa05f249638a4f43b84ae20294409b90b9f68b36e7a9aa771997129229"
metafile = true

[[files]]
file = "mods/highlight.pw.toml"
hash = "554fc5e8aba13353c9b9d4ff066ec6aaf1bd559550633ef4ace120541cada94b"
metafile = true

[[files]]
file = "mods/iceberg.pw.toml"
hash = "cf8b70a9aee53147acfa4f6dd545baf2a65a597dd456f04c65e8ce378afea11c"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "682e83efe5ebc5db45f4f74afa47b0f5f82a3ffc38b5c548332c7bad291bbaa0"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "c40df2a317ccff0ece3818028bec09727154486051a42bfb42765c9ca3420038"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "ca8e90d44722f5fe35427d7ad1f7f34ce78155031a6dc76dfd11dd4064873693"
metafile = true

[[files]]
file = "mods/irons-spellbooks-arcane-essence-blocks.pw.toml"
hash = "e87d519950f0d9362c919a9afb92688769b321a21b578c01a6d94645dd947cf1"
metafile = true

[[files]]
file = "mods/irons-spells-n-spellbooks.pw.toml"
hash = "5d7b8339ae3f6195887c1b81d1716fa98759945a114a6dbaaff096a6f385dfaf"
metafile = true

[[files]]
file = "mods/item-highlighter.pw.toml"
hash = "9163b758163681f75e2048c798be880c50392684b127d7d87f42ea588deceb62"
metafile = true

[[files]]
file = "mods/jade-addons-forge.pw.toml"
hash = "8cd8400cb4e2c5ba60c8a359a7b6ff501078d2056eab0aba7f6b0ac77b7a0694"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "652900870d343dda5683456934ca76bf176ea54da73d9883d8a13c9b3cae2fac"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "44634200be079994523f61e1a4b2878f4d2e1b59d52378391aa81192b1d15bf1"
metafile = true

[[files]]
file = "mods/just-enough-beacons-reforged.pw.toml"
hash = "7ca67e45e5ff8092ea662cdab8d9c30341b69a5f6fcb3e9a42557ed3867a01b1"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "5be22210c5f8f8b3f15159aadbf8f264cfec52309a37479463bb08904d7fe157"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "7905c08f37d8ebde50a5330a7dd10029de6259b0cb8adbde1170d93ea20218a7"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0033c5a00c46d5d7b6cf77b19fa76ce5c78a613f3128dcadb3588fa5841ae489"
metafile = true

[[files]]
file = "mods/krypton-foxified.pw.toml"
hash = "b843ce75c788f0720b6e23d9021ce55d37415d72802ee60d95bd2fc5809ba96c"
metafile = true

[[files]]
file = "mods/languagereloadunofficial.pw.toml"
hash = "76b766b465351c6f1f57bbf68f72b66a59655d2e9a150c79b3f691d79ccbe1de"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "1348d9c5ff54859303da087b90b01535e586aeeb2999b3d81ef7e9ff1af68833"
metafile = true

[[files]]
file = "mods/longer-chat-history.pw.toml"
hash = "bedb744feedeb8fb5af830d4c22b934c11f455588dfef47a5cf3c951804d5f9f"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "91e6a0e562023e927ca1c56bdfd5df673609cac23528f768a83afe3674cdd0c0"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "702df8b679041c5f459da5a0dc456f70de336810bc69ff726d8c925bf484e99c"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "494d362db9766b5cf594109dabc35c50d78c99699d68ebc87e0d6dd51e19c244"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "3990757ad1f7cc8a3b92ac5f3a5e219a5c80092240ce8a3ad4f1b9a7a46b3817"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "1d09669cac9fad91c06b914728f25b93aa4114cc61e336b3d03ff7025c849ebc"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
hash = "4f3d43b696c5081e35eea3cee0588efd5f6b8d547b603b24645fe1edc0b0ba3e"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "1456ea6fcd89848419f1747e1441065ba591469099af54889106ae832959f627"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "238dde67a84fb867a6dfde2118d36371cb85420b3ac638976aa32899195af11a"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "409cf6c16cb9012c1aa933a1f2fda6b526a9476aa25584314629c78a5ba10a64"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9dff522b00f5269538d0351536f34b22384996de30be454ef1369f1b1e5c1aeb"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "5dc059422613b5645cb00e32d3bfd53de428c4939113d11ce2c844cb54165da6"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
hash = "d424a9260ef51bc102e56f0423d91dfabb739ccca8a86eb1c450ea631b739280"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "4304df902057ed0f5f210646e0552570d53782aae21f94eeafaeebdf33a51cf3"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "b30bf3e10fdb43cb451091d4cc8ff88081895686c492c1bbff50ce0c74a3e85b"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "87fb28047d648087f2fe4891ddf9d3c394b9c5c29eaf4f3970fb7c32520e6fcf"
metafile = true

[[files]]
file = "mods/playeranimator.pw.toml"
hash = "c83705becd548879473132552de960f9d5975fa0edaeeb2d4665a4e35457423e"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "74c4147419e31244a156285fc030ca773e7f35c69a04ad15cc5af68aa4db72b5"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "7750bf1c0a66c843a06f07bd0ed7157d14ff0958e19426aadaed6ecf3034af65"
metafile = true

[[files]]
file = "mods/projecte.pw.toml"
hash = "d5888ffcf49a86a8796d575aad15e98c148a65bcd71c9e06670b31aa40668e9c"
metafile = true

[[files]]
file = "mods/rechiseled-chipped.pw.toml"
hash = "33ff19e15d3eab2cf108508a9a455311fea71b4a713dc5b4c2b96e46b9327852"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
hash = "f70753b73b9baee1550e932231cdca1da45c4516c6b7b8763a2a164e0bf375ce"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "6f8063ef991eb6bac1319c2bb07fa56a848985a198b5ff45310342d1e00daeba"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "27721caca5a03b743bf25888e1d984142948069dace31453f103f94f7f24d2ce"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "c0b066684294c33972d562e0cb08ea17b2d31bcf86cd1d6c63b8e968f0eac7a2"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "ce9ddada6ffd55a512149cc474c6a453281a997a5fdf1b7b4a2cc73f875e704a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "e1bac320595f51e87fa3eb8daf3a286d997ceaf21673f94d9d588cdb0fdff106"
metafile = true

[[files]]
file = "mods/simpletms-tms-and-trs-for-cobblemon.pw.toml"
hash = "f8ba20a06c8391dedc25741ab2817e1af2bfb9a182eee248471dae4b41eb7d77"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "c83dd1d3c2dde6081e6f89246fb3b89fa29734f5329f4cd6d949a5c0da55f35c"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium-options-mod-compat.pw.toml"
hash = "cef2df389d9ea783c940ff614e987223aa10b7653f8228d2f899071a151d60f6"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "c5687771065e4a43266b38018cbdf142b216916dd73aa6532b8282e3d0f06b9c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "819b3e7402252905b6fe89743589df910c84995e8305995cb61d1f32fda2a2eb"
metafile = true

[[files]]
file = "mods/stitch.pw.toml"
hash = "87efe123ee3fe0133a4e951f110a98a32b16068a3033f2c3a0dbed574ff48cf0"
metafile = true

[[files]]
file = "mods/superb-warfare.pw.toml"
hash = "b29c53305ef94b02ca14b9a44ce37da9f69c5e3729ddfb09191c15fb014dd20c"
metafile = true

[[files]]
file = "mods/superflat-world-no-slimes.pw.toml"
hash = "b33abab4c92ce00a5f51f1bd7833ad88ff34e8bbe71e216a0a2949335ae85a2e"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "62bd7012826fdcccf17a089055be67f87fb7335c88e73efc52bc9e51a1bf3188"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "2c297fb87d09bd4203399e865d48a10aa82016c53b6767b10b43726e111a3566"
metafile = true

[[files]]
file = "mods/tempad.pw.toml"
hash = "9e2a80744672102d9f5cde3366e6089e70f5c46309bf0533bc33cc96701c6adc"
metafile = true

[[files]]
file = "mods/tims-ultimately-comprehensive-cobblemon-edits-of-destiny.pw.toml"
hash = "dd80c32544fa53ce16cd3bad42ffa8440ce6d7c2efa4a63940804d10629330da"
metafile = true

[[files]]
file = "mods/txnilib.pw.toml"
hash = "8ed08d6a636751925b06a48feb98007e04c313fa936466b623021819fdeb26aa"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "75875de6233b9a09724376231c012fb01359f6718e28532418fe2e4853bc67be"
metafile = true

[[files]]
file = "mods/visuality-forge.pw.toml"
hash = "753745ebdd476d1b75252027f8cbbbba7334a71c49f9803652a53f5af111232c"
metafile = true

[[files]]
file = "mods/waystones.pw.toml"
hash = "83c2f33a6656799f209ee75d63da20c4e692202371a221fd853792dad6113d7e"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "8ab75b4183933206d15aec33cdd3d94485c9192ae507fb9e9a36d17a6feb1213"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "396d7308b4f919a25f9d12ab9476c756bb7c3fbca3bd8dc5d45e92ed3c77b9c5"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e2ab678518f876a978414ec1b9c88896d78dcc49ee7bfefa0acc165d5388c7be"
metafile = true
