hash-format = "sha256"

[[files]]
file = "config/Mekanism/additions-client.toml"
hash = "7bf81e79c36e1ff5ceea435f5493000f27821b1c72329ea4298955609c6591c8"

[[files]]
file = "config/Mekanism/additions.toml"
hash = "0788522bba20d8e72bdd355a0ea0e11810268956f7dbb0b45781d2bbb79b7347"

[[files]]
file = "config/Mekanism/client.toml"
hash = "096303223e1f1cb384f3fca3d0a825857aab63608013d4300d21486e2ea8e53a"

[[files]]
file = "config/Mekanism/common.toml"
hash = "aded0937dff550c18f0656661333ad9f37990cc5d38e6840497cab3ff7a266fc"

[[files]]
file = "config/Mekanism/gear.toml"
hash = "02d464d81e33020e6ad28e0021829f1727f02821014c251afef14cfc85c99660"

[[files]]
file = "config/Mekanism/general.toml"
hash = "930408c80a41c9e7e39b2c31f7764b85e61d88b382f8bff3992404585f1d0bc2"

[[files]]
file = "config/Mekanism/generator-storage.toml"
hash = "c28e7cc320f69327d5f2affdd2d3cbb85ffee6ba577a75a98618cedd02e564f4"

[[files]]
file = "config/Mekanism/generators-gear.toml"
hash = "9dfdefd08e85a5089eb6ba33478913e1c96d984e18a5edcf9b5310616fee18c9"

[[files]]
file = "config/Mekanism/generators.toml"
hash = "dc3b90dacbb87a5ac278007bf806e63100e47f419492a5a390a55471f6724c08"

[[files]]
file = "config/Mekanism/machine-storage.toml"
hash = "5762af5926b2312aaff9bda0cbbb44748d6ad2ed1b12a5d19af28407bc604dc6"

[[files]]
file = "config/Mekanism/machine-usage.toml"
hash = "331ae2bd0031e3d8c65f3572f17bf81af186363c4a4a630e4184f6d427d2f136"

[[files]]
file = "config/Mekanism/tiers.toml"
hash = "b5fb9d3325f776146cd6d891be2ff373a406494fe51e4cf2551b360241210d26"

[[files]]
file = "config/Mekanism/tools-client.toml"
hash = "b12d9391ca6da6d45a0247daac7dd21a1400f42fccc51edd180e18459ad5fe00"

[[files]]
file = "config/Mekanism/tools.toml"
hash = "6aa5e61a9b6280310e85e127431166fcb4d3826cf2b7ea07d2b42b75c25ab87c"

[[files]]
file = "config/Mekanism/world.toml"
hash = "54971d6ffd03a2bd66d146d77f421e07133752f7b9c2f66a0a8196c7a85bac50"

[[files]]
file = "config/ProjectE/client.toml"
hash = "89fa546c9262ef68e302b89cf2f22c02834d00abfa5ccd1159df85e8bf902f14"

[[files]]
file = "config/ProjectE/common.toml"
hash = "f6f11cf5349aa7c6c94d3596b86d574fe6302103ff8537e3747a3ea622e90360"

[[files]]
file = "config/ProjectE/custom_emc.json"
hash = "d0cae89f2bfff50daf3aec1798559241e4224f50acda81bb5d6ee589df07763f"

[[files]]
file = "config/ProjectE/mapping.toml"
hash = "b2c9b44f6f0c6d16975b79ab0868390cde74a559f5fddd5a19bc0b6dcab6cbd5"

[[files]]
file = "config/ProjectE/processing.toml"
hash = "08f95fa6aa91e358f6d64382a07ec040467d66377ad894c23d7503f8bb816a3a"

[[files]]
file = "config/ProjectE/server.toml"
hash = "70a1974438b0b282b0b60a4e11dbb7329465bf41ddb9472920f51072d21cb4f8"

[[files]]
file = "config/ae2/client.json"
hash = "2b4592dca53600318a7123befb79193bd261a44739b203d3e01d56eddbf2e27e"

[[files]]
file = "config/ae2/common.json"
hash = "89f5a0f747928712147d03fff0a2b1da4285bfad60ac5ffe18de665b2a0c45cf"

[[files]]
file = "config/create-client.toml"
hash = "6bdffc741647463db2865247814706c6aed9dd2c83ff0c79486b1572f926e67e"

[[files]]
file = "config/create-common.toml"
hash = "6c0f6254798808bce8079a1cfafe4d6c082cead42c51d1e3121f3580f8a44eca"

[[files]]
file = "config/createaddition-common.toml"
hash = "80af49f558c10917cc7772f6ea0e5de3898afbc1a5b8ad46f39c0f9fc7ba64de"

[[files]]
file = "config/curios-client.toml"
hash = "1ac04b541d19cc58791e5ceea4a46b7e1d75a2b4b2d5e359b9fcab606e5ef750"

[[files]]
file = "config/de/mari_023/ae2wtlib.json5"
hash = "e9838cc6c67a746008e2c8bc88577be4c350d4f990ee5ca4861f07bce76e36ea"

[[files]]
file = "config/embeddium-fingerprint.json"
hash = "69154c347edb1fafb507b1b52ea23e5ccd372f6e080019a6188c06d5fa5f92b5"

[[files]]
file = "config/embeddium-mixins.properties"
hash = "09ff183e061d93b79514bc171bf9118497578757e7a5c45946039487656e2619"

[[files]]
file = "config/embeddium-options.json"
hash = "ebc94577ad1c7494c3bb5d2947d8166a07ddf26a8559f449a105e637045bd8c0"

[[files]]
file = "config/enderio/armory-common-1.toml.bak"
hash = "be5a4f4a1b5049bfaad1c8892278d27d46f7a7452be6f83e2b58c054f35b70bf"

[[files]]
file = "config/enderio/armory-common-2.toml.bak"
hash = "be5a4f4a1b5049bfaad1c8892278d27d46f7a7452be6f83e2b58c054f35b70bf"

[[files]]
file = "config/enderio/armory-common-3.toml.bak"
hash = "be5a4f4a1b5049bfaad1c8892278d27d46f7a7452be6f83e2b58c054f35b70bf"

[[files]]
file = "config/enderio/armory-common-4.toml.bak"
hash = "be5a4f4a1b5049bfaad1c8892278d27d46f7a7452be6f83e2b58c054f35b70bf"

[[files]]
file = "config/enderio/armory-common-5.toml.bak"
hash = "be5a4f4a1b5049bfaad1c8892278d27d46f7a7452be6f83e2b58c054f35b70bf"

[[files]]
file = "config/enderio/armory-common.toml"
hash = "be5a4f4a1b5049bfaad1c8892278d27d46f7a7452be6f83e2b58c054f35b70bf"

[[files]]
file = "config/enderio/base-client.toml"
hash = "91330d6c548c114e55275ab2adb0b4ad51cdfa877359967e9b930f492546c310"

[[files]]
file = "config/enderio/base-common-1.toml.bak"
hash = "4a895e3f8ca027c6e8644412402cd1a5518685ed107ee0f9b8812becd11ebc49"

[[files]]
file = "config/enderio/base-common-2.toml.bak"
hash = "4a895e3f8ca027c6e8644412402cd1a5518685ed107ee0f9b8812becd11ebc49"

[[files]]
file = "config/enderio/base-common-3.toml.bak"
hash = "4a895e3f8ca027c6e8644412402cd1a5518685ed107ee0f9b8812becd11ebc49"

[[files]]
file = "config/enderio/base-common-4.toml.bak"
hash = "4a895e3f8ca027c6e8644412402cd1a5518685ed107ee0f9b8812becd11ebc49"

[[files]]
file = "config/enderio/base-common-5.toml.bak"
hash = "4a895e3f8ca027c6e8644412402cd1a5518685ed107ee0f9b8812becd11ebc49"

[[files]]
file = "config/enderio/base-common.toml"
hash = "4a895e3f8ca027c6e8644412402cd1a5518685ed107ee0f9b8812becd11ebc49"

[[files]]
file = "config/enderio/machines-client-1.toml.bak"
hash = "160f1070d4ba2b575458eccabcce27a66d8d8942e66326e089436eedd95f6f63"

[[files]]
file = "config/enderio/machines-client-2.toml.bak"
hash = "160f1070d4ba2b575458eccabcce27a66d8d8942e66326e089436eedd95f6f63"

[[files]]
file = "config/enderio/machines-client-3.toml.bak"
hash = "160f1070d4ba2b575458eccabcce27a66d8d8942e66326e089436eedd95f6f63"

[[files]]
file = "config/enderio/machines-client-4.toml.bak"
hash = "160f1070d4ba2b575458eccabcce27a66d8d8942e66326e089436eedd95f6f63"

[[files]]
file = "config/enderio/machines-client-5.toml.bak"
hash = "160f1070d4ba2b575458eccabcce27a66d8d8942e66326e089436eedd95f6f63"

[[files]]
file = "config/enderio/machines-client.toml"
hash = "160f1070d4ba2b575458eccabcce27a66d8d8942e66326e089436eedd95f6f63"

[[files]]
file = "config/enderio/machines-common-1.toml.bak"
hash = "ef8337f6ac71b2bba20ae3cb57e3f9143bce36f7152233e842bb5f7f94f9db66"

[[files]]
file = "config/enderio/machines-common-2.toml.bak"
hash = "ef8337f6ac71b2bba20ae3cb57e3f9143bce36f7152233e842bb5f7f94f9db66"

[[files]]
file = "config/enderio/machines-common-3.toml.bak"
hash = "ef8337f6ac71b2bba20ae3cb57e3f9143bce36f7152233e842bb5f7f94f9db66"

[[files]]
file = "config/enderio/machines-common-4.toml.bak"
hash = "ef8337f6ac71b2bba20ae3cb57e3f9143bce36f7152233e842bb5f7f94f9db66"

[[files]]
file = "config/enderio/machines-common-5.toml.bak"
hash = "ef8337f6ac71b2bba20ae3cb57e3f9143bce36f7152233e842bb5f7f94f9db66"

[[files]]
file = "config/enderio/machines-common.toml"
hash = "ef8337f6ac71b2bba20ae3cb57e3f9143bce36f7152233e842bb5f7f94f9db66"

[[files]]
file = "config/fluxnetworks-client.toml"
hash = "e7d0eaf3d5fef7f659026ba60fbcb7380e6c7af28630a27af73ae22118cc0594"

[[files]]
file = "config/fluxnetworks-common.toml"
hash = "4feeb0ee5fdbfe72a34b0db3caf9e0d531f741a5b2ac00f57ddc160273fac8a9"

[[files]]
file = "config/flywheel-client.toml"
hash = "0a70d58a4a562c2aa2945a3883d35fa3a8e90d80eab9d6b2db3be6103f71b9b2"

[[files]]
file = "config/fml.toml"
hash = "953c6cb21eb0898aa077589b474b0eec19db6ed1052e5d59fe2a25cba89b4ded"

[[files]]
file = "config/forge-client.toml"
hash = "887ab56b28b84932643280912fe29bd66e3f2c7e80c31b114925bfe7a670601b"

[[files]]
file = "config/ftbxmodcompat.snbt"
hash = "774631c740366a8dfef9c646d5f60a9939299f3627180ab9ac4d540c76af4081"

[[files]]
file = "config/jei/blacklist.cfg"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/jei/ingredient-list-mod-sort-order.ini"
hash = "a70c3eac6f30be7f0f074685d1ba47f29710fe484bb48d59a7c87eec4e50024d"

[[files]]
file = "config/jei/ingredient-list-type-sort-order.ini"
hash = "5ab6c4af6e3d732cd86bd73264d9836ae6cd151337315b89d1156dcf725a323c"

[[files]]
file = "config/jei/jei-client.ini"
hash = "e29c72e0fec5860b6cc5a4466841e4092a863002e8f56247569c83fdfe494a09"

[[files]]
file = "config/jei/jei-colors.ini"
hash = "bca5b02f5689992eedefaea160cecac8fd69ee8ae7cee403f5294afbe539e8ce"

[[files]]
file = "config/jei/jei-debug.ini"
hash = "8f986a34dbe2053ece09b3f6d7635e38b17ea5c49befb91e87d2c2e1a44c8b1a"

[[files]]
file = "config/jei/jei-mod-id-format.ini"
hash = "8f2761840207e6e133df740cd06303e52c711f418942300073cf58827a06b989"

[[files]]
file = "config/jei/recipe-category-sort-order.ini"
hash = "3242e39d266c28e6432ceb57fe68557b830bcca451ba38f17a4213c29f1b8215"

[[files]]
file = "config/project-expansion.toml"
hash = "83b7b850533ebe00420783988396329875d23af28feb42f3a51d3bf0d772da37"

[[files]]
file = "config/railways-client.toml"
hash = "21e8cb0869daad0b795bc8a18bba16cc13bab327645480ea39e3ad841c037d3b"

[[files]]
file = "config/railways-common.toml"
hash = "58f7821842631af9ec8bcaddb60526b81cd1b9ad63cbba87c83c70e53c3a9b16"

[[files]]
file = "config/resourceful-config-web.json"
hash = "33ea04990baaf8ebd80136966d6655113d1e785e19afa73a31e96aa6e9984867"

[[files]]
file = "config/sidebar_buttons.json"
hash = "e06430efc23d0b56b4a009b16a2dbfcebf574c90de700f28c7ff4ffcec545c6b"

[[files]]
file = "config/sodium-extra-options.json"
hash = "be4747ae45241c9bf90031ea61b88188c776b8547d9041feba62d18c4b218e3b"

[[files]]
file = "config/sodium-extra.properties"
hash = "a2f1b47c1eaa119ab34727f1d43c2506cb3d7f17ba8fb4efb49e20c8e0b58e70"

[[files]]
file = "config/sophisticatedbackpacks-common.toml"
hash = "b377e97ca3d8ae8560448b92ab820872d7c11bef0ca52dcf3f4901b44c6ddca7"

[[files]]
file = "config/sophisticatedcore-client.toml"
hash = "293088be5b4d13e99f6c12a0aaa7b56f0f9db5f9abbc615086989b689b3827d3"

[[files]]
file = "config/sophisticatedcore-common.toml"
hash = "fc5d1d8d5c2e9aefd59090e9686e821d2368a59860f1d60cdafe53718fce53de"

[[files]]
file = "config/tempad-client.jsonc"
hash = "d56d8431a85eeabaa8007550f4557112b813922a9036414cb6eea11fefd753ae"

[[files]]
file = "config/tempad.jsonc"
hash = "103249151fef996292834f3c4628d929305097d6f4f9da348870a17c167bcd6b"

[[files]]
file = "config/xaerominimap-common.txt"
hash = "12d59cbd75c19a2bfb7f837f161f762e6136e834b07d3c3c5bba806a66e34bc2"

[[files]]
file = "config/xaerominimap.txt"
hash = "3ea3466b8e433223910c4f8adb478fb5d3cd6884191a91ffdd32712e7fe3ad57"

[[files]]
file = "config/xaerominimap_entities.json"
hash = "b8ddf54611a9ab8c53177fc0d062321e9e731192b65b9e50d0fcb38a86a91696"

[[files]]
file = "config/xaeropatreon.txt"
hash = "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"

[[files]]
file = "config/xaeroworldmap-common.txt"
hash = "d1f01c1b88e9f0273da1a90cd0c5d0ff62c2313b7ef4c901993aa8cafa84e5d6"

[[files]]
file = "config/xaeroworldmap.txt"
hash = "6cae8c6c64eeebf4dd15076b8f172a440bf1ece460aef63d3abe206e2d45fe8f"

[[files]]
file = "kubejs/config/client.properties"
hash = "cfdecd37667b6e32b6f2595594bc867ba6ac58137a57a9c41589b840d6823afd"

[[files]]
file = "kubejs/config/common.properties"
hash = "b18543354182540d936e1c6e231a40a415ae77716d463b6b1c308096b3efbaca"

[[files]]
file = "kubejs/server_scripts/crafting.js"
hash = "e053a44b53c6d70f3f982355e7d9ee3b460290404ed2c4d9a4c400933f0bba0e"

[[files]]
file = "mods/ae2.pw.toml"
hash = "795d8e7f803f53d432f1f9440d3edccdf891f9799d448c5815283fd6086b2a3c"
metafile = true

[[files]]
file = "mods/another-furniture.pw.toml"
hash = "ba45971e28bf00e0dc80a43d0422c6be3ba67924af1dfbfd7d41b0c746dbdba4"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "5d03b477df607fc4fa5cde634a6e870413ab097ff9222d2f0a465ac0fbcdbea4"
metafile = true

[[files]]
file = "mods/applied-energistics-2-wireless-terminals.pw.toml"
hash = "610eaf47cffb21e153bbe5f26fb6dfb7f9af5a2d741b22005504f28602d3ec35"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "b7321e670cc58aa8062f7cae470c9806c2ed83680ca598df5fe6e75ab40df452"
metafile = true

[[files]]
file = "mods/argonauts.pw.toml"
hash = "c9a5cef8a5379ac9d4e18678d4f33b3844a2b51ccfc9c1ec23dc4064d9ed695d"
metafile = true

[[files]]
file = "mods/cadmus.pw.toml"
hash = "90165200040ed24a7b8f25ea9f19e4715491b3d31c657196982a91bd557c6cdf"
metafile = true

[[files]]
file = "mods/caelus.pw.toml"
hash = "958d92f2c763942e7846f4c77b675c126cc8738a1dbc1a6f53390fa0d44b1a10"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "38cf4a76862812fefc9b1ae0b8fac02b3f706716f3228eb859b511950273e791"
metafile = true

[[files]]
file = "mods/construction-wand.pw.toml"
hash = "119a7506c39a296fc3cd7d6f874c08b2664082811ba95daf2b98f27f398fb980"
metafile = true

[[files]]
file = "mods/controllable.pw.toml"
hash = "a43401d685fc24595cb18e5a51f4fa7af4a4dee2ba7bf7879a08769b037495fa"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "28cd35abd7f84a4d2f04fb50128bf272cafeac126dbdd6c20cb9c27eb0cd3d76"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "c464b21ac8baf5ed1d22a0c4bacfcf24977e04dc938add65a2a93bcaf704c22e"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "0228a91f523d16f54e263e336814eba86e0d2b0d5326e14ca5d8ce4a4f374e30"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "e1e959139fd83cf1ac7cee6296c7f535d8c3ff76e78a30b915571fadc4f04139"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "6476e5fd12fa24e1d0c21aeef67c27f13af8c6e5391b65815924ff664fc3e653"
metafile = true

[[files]]
file = "mods/elytra-slot.pw.toml"
hash = "b6f44d5d64a041adcad7fd12f542d6dab5ba164f009650ef5b950d0287f7b252"
metafile = true

[[files]]
file = "mods/enderio.pw.toml"
hash = "d716522fe0f486fa2d0dcfe2ba4d55a3d28c5f3f043cfcdf0cb90add23c45ac6"
metafile = true

[[files]]
file = "mods/flux-networks.pw.toml"
hash = "c03ad50ab5df88a251e335fa8c6a3cfb0621279c76ce9661969450f501d6acf4"
metafile = true

[[files]]
file = "mods/framedblocks.pw.toml"
hash = "e6defe3c20e412bfae7de25c0908a0b270fb3754bad2be9b16c54b3e2e7aa2c6"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "0d43726a6fe83f1064237efbe1362bb15110a5e5dffc2d953b43e1893cb00080"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "7b460acaa50fb6814f31028a47d6e885c0faf7b6fe1f3d303eec85314920147a"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "c0a0a1e85892a9546c1c69761db4d676e8ff63f67dd203b9d1ad1dc0b07d7b0f"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "3de2843a7072f8e7308ba53b1ac2b3f1a38312d4acf69d5cf116c9ac684f3778"
metafile = true

[[files]]
file = "mods/kubejs.pw.toml"
hash = "eea2ffefd25dda2c4daa1b100a37c6bac60bd087302637635f64e5ad1f4ae096"
metafile = true

[[files]]
file = "mods/lootr.pw.toml"
hash = "1286aea4a30d745cad727bad3302201d177692f690791db04b09db522631231d"
metafile = true

[[files]]
file = "mods/mekanism-additions.pw.toml"
hash = "db0cb90566275af969156c109a7c706dfeae5976e1f7083b47bfca1fcd3fb011"
metafile = true

[[files]]
file = "mods/mekanism-generators.pw.toml"
hash = "70b08746769d617cf1138e140d45f8418c579c505da8244a6db569b87efe0fa7"
metafile = true

[[files]]
file = "mods/mekanism-tools.pw.toml"
hash = "65a209b708790b508ef15204c507a85c32322759c6667bed98564561d9af42bf"
metafile = true

[[files]]
file = "mods/mekanism.pw.toml"
hash = "22ef61953f3dbf520cc89eac5c6ab9a046cecd46254f37b04e80ed01e9e8a6fe"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "038fcb9985adaa5756f9236c84634a1fe546eb4f4c54f2293d61e1989c114870"
metafile = true

[[files]]
file = "mods/project-expansion.pw.toml"
hash = "004bb0c5e819b6ef8a42c8c3ce65333dee9bac1fe8397424a6ac3ad5032706ff"
metafile = true

[[files]]
file = "mods/projecte.pw.toml"
hash = "26b6891625bf09317245200e3adb871cea00dbd41859d68cf57062544c0e6041"
metafile = true

[[files]]
file = "mods/prometheus.pw.toml"
hash = "a1ff68cc09b3ab85ed8307eff1dfc8ccdf4d3a8dd718bf0949eba0f047afe5a3"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "92b0bc142a7cbc4af73ec922b72e9ab6f7b41cedc35a7dbbd49bbc3d66f88fcc"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "1b81dd66034ae46b30ca85679c1482596caf26ca6e71c820f5cdeade760e5b93"
metafile = true

[[files]]
file = "mods/rhino.pw.toml"
hash = "09e53b8ad971d1c870a94da1a4437335db9307b780073030bd445ee71e8a86f9"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "87f65e6facf6f4cb44331ad7700f706bbbe6376678bcdac3feedc3d802d10732"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "ce696c09e68dd81a8b08a3e6a0fdc484a5ce0b2d9cde16ac71df9b86c0ec1de5"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "73c867ebc7096e77b78549f09aff1d10fb5951d5748ea7cefc9703769bda3eb5"
metafile = true

[[files]]
file = "mods/tempad.pw.toml"
hash = "0d53d6bb037a8c8411c3524f49a9a26c2462f9cd33fdf38f345e902dcb711b83"
metafile = true

[[files]]
file = "mods/twigs.pw.toml"
hash = "dad1eaefe4050aa29a82958c4f956ec28a140791d458e75757fef8b939210972"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "e339cae56687e4f17948f58f32374a94c3896c825b30be472e394b906ba72d49"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "5fce733f5d600f5f27e995ae61b76a46c990105424aad0c0f7e4dedaf608ecac"
metafile = true
