hash-format = "sha256"

[[files]]
file = "mods/advanced-loot-info.pw.toml"
hash = "204ea06e140602dd7bd58e0987c4b7bca891adae452820d595409e1b4273ecb8"
metafile = true

[[files]]
file = "mods/almanac.pw.toml"
hash = "6b1de417a7fa934847bf002b75acd00d48637bb3484ea468799354b612658775"
metafile = true

[[files]]
file = "mods/ambient-environment.pw.toml"
hash = "92a2077fb3d27df20550d579d14c43b1feaa605796b217efb7a9d4bdd727f3bf"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "3213c881d019cd8f952f738c10d5a950ee52ff0084750b81f656a58a4a78515d"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "ea336d25c3e21ef168aec20e1ea470c96949ad29632646ee8e8ab0d74b4bbfc9"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie.pw.toml"
hash = "574807cedb57ba6360060d6bf4a359cea9d00bf8700caee866d48ab949005b89"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "9605764353450757f20e153abdcedf770b4affab703869724b17454d23a45039"
metafile = true

[[files]]
file = "mods/better-advancements.pw.toml"
hash = "93c4acd165a291c6d1e69c27b05b2747afc926b38a414712263fbc95f42da323"
metafile = true

[[files]]
file = "mods/better-ping-display.pw.toml"
hash = "cc2e6dda94a7a6f5487843cafe569d8044bf9482cbf03f062cf4595f1fb05281"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
hash = "e1f1588b18947699ddc9b4f7c5b5406c5559155b8cb52dcd0f203c07c31cd0b8"
metafile = true

[[files]]
file = "mods/better_tooltips.pw.toml"
hash = "17f4ad375a6446bb2ded49a587af0618e86dccdc1ac965bcf0f02c6287dbdfd1"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "4251cec80cb5687d2b0b2c2fe063b1ea9a7511c83ed22824342770919ea91feb"
metafile = true

[[files]]
file = "mods/cherished-worlds.pw.toml"
hash = "63f417eca4f251f85a5ae512394cbb9fa88dfdfb2b934b94637ba8b7dac1a831"
metafile = true

[[files]]
file = "mods/cit-resewn-neopatcher.pw.toml"
hash = "2845c5e3f38068f06a51bfe759dfb683f810d3737f88e332470a1c4c30ffad74"
metafile = true

[[files]]
file = "mods/cit-resewn.pw.toml"
hash = "6d511d91e17e09d36b0b0c7065b07eb604146bc9f3df0fbc932948aaf33aa440"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "75181b55e0407d1fca1e2f346c6501f919f5109545990ddfb66db9cd1b771f8a"
metafile = true

[[files]]
file = "mods/clumps.pw.toml"
hash = "2acaff560bbda5741538528a2967355ec86a8f7564adba0b2316989c66892374"
metafile = true

[[files]]
file = "mods/cobblemon-mega-showdown.pw.toml"
hash = "92b785cf953bb09b2629dde4d160c47cfabafad5c725976d69dcc524dc1add58"
metafile = true

[[files]]
file = "mods/cobblemon.pw.toml"
hash = "e3cb1eb238192071af93f764e3ff2c493f4f437802bb56273f664bafdea13f1d"
metafile = true

[[files]]
file = "mods/connector.pw.toml"
hash = "9f920c5f1df2577cf374285e4aad4f2982a30ea2a3da1cf7ddaf25e04b3a2e31"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "6f6ecb72aa956a4461add613a717d751879092c6ef30bf1e4c8576e165324da6"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
hash = "d41d4ec1f45e8df91975f0484a52489edaf61defbcb5ad8e5ee67ba2b79a3ffb"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "36debf7653e95a855b4fedacc19027cf2e01960fc0b6d55ef2ffbffbcb455690"
metafile = true

[[files]]
file = "mods/default-options.pw.toml"
hash = "1d99ac75f92996ec9673e39c012a51dc4b05c48ef7bf672ccaf5e7464a1a3d13"
metafile = true

[[files]]
file = "mods/dynamiccrosshair.pw.toml"
hash = "4e6cce2a40f56a58a5dffa924b05a27b7cc618c4c9afd611e5a2ff247a5a1065"
metafile = true

[[files]]
file = "mods/emi-enchanting.pw.toml"
hash = "ff029ee6fc50f2696e96cdbcc696f42e75b483c9d7b83f2b1447dcf5c865e664"
metafile = true

[[files]]
file = "mods/emi-ores.pw.toml"
hash = "0b921f73d5b1ad6615740956567d6cb06950f5520f094dbb7a045bb4bd5ba309"
metafile = true

[[files]]
file = "mods/emi-professions-(emip).pw.toml"
hash = "0477d572817d9de3a5569109a8d07a2e519af9ccf0e8236cae621369afbc6e4c"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
hash = "d3c9b48d7caa2ed964e5d1a4dab1da5655c63f0a7e4a59231c4369be7ffc30e1"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "0b380e24e46e328c362bda7cff892c5b0e471789ca8c429fd2a588eaf63b8712"
metafile = true

[[files]]
file = "mods/enhanced-attack-indicator.pw.toml"
hash = "5fd6cb9f5052b6b7891f2a4ab8c874f125a263a4b03cad5a3b2b3f80c57abc6a"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
hash = "3a4e194e945214cc457178f48e65b9ab6a8201b6d15b9736cd673324b70b6edd"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "5c58b5f90359fa2516855ddea5406998e7671889b4c89c46fec1f142e79357a3"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
hash = "65cd00e90de065e99d13352fd5d8aa3bc28d062b9dc935cf1da914a2047b2208"
metafile = true

[[files]]
file = "mods/fallingleavesforge.pw.toml"
hash = "e5125f8f2709fd20f8182fade3d7f9e7129872c63f042c5489c6eba4733b6b49"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "05d96d5b17399f048469ff4b44451eb8d99cc7a2a075ff55718c397cb508b0c2"
metafile = true

[[files]]
file = "mods/forgified-fabric-api.pw.toml"
hash = "cb56550a957dd44cab4f9102aa588cd22421cd6b4099a03ac7b1b167c23c0f13"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "d102275300c327312e3ea9afd6844d4627637cffa68525af69951fe2eeca33b0"
metafile = true

[[files]]
file = "mods/invmove.pw.toml"
hash = "2235350d913f0e3ded91a238a5224d35a883c80dbdf1fd9d97fc363b20137ef9"
metafile = true

[[files]]
file = "mods/invmovecompats.pw.toml"
hash = "dc5df58a2dce94aaeab2b63b3b73a0d8c7d05ce18b1edb6db3a0e8198313e5d4"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c3c06a4839ecfd4717686f7394396a4fc66b7a2e8eabbdd51f23ab2a1099cc1e"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e1186ddc953e1446af3ba58cbb80ddd0d2315c1571ed5438f5c03953edf0b656"
metafile = true

[[files]]
file = "mods/just-enough-effect-descriptions-jeed.pw.toml"
hash = "ebaa44f5e5a3ee400288b72a2a67b12f741361a7459ee0505272c93fa8e91932"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "054a1887da4f14b791910660a2a7a2035ac1382461b881a65fe07b224c03735f"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "0a983d1515e1713d1a0ae7738091909101c368be2726a446e4ca29c62fe555c2"
metafile = true

[[files]]
file = "mods/krypton-foxified.pw.toml"
hash = "b843ce75c788f0720b6e23d9021ce55d37415d72802ee60d95bd2fc5809ba96c"
metafile = true

[[files]]
file = "mods/lambdynamiclights-unofficial-neoforge.pw.toml"
hash = "3003180f2f32aa8aea9bc786e935e0b224f509f0131df625090c12f528d8ddc7"
metafile = true

[[files]]
file = "mods/languagereloadunofficial.pw.toml"
hash = "76b766b465351c6f1f57bbf68f72b66a59655d2e9a150c79b3f691d79ccbe1de"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "b8ce87d9a7164676e68e69e9e6706cd6e9123b1fe740612b1ba39b43ce8675ef"
metafile = true

[[files]]
file = "mods/lmd.pw.toml"
hash = "edc75ace846ae34c1cb4cf4a44106e1fb035b1eee0432765a716098c9a4b5823"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "9dff522b00f5269538d0351536f34b22384996de30be454ef1369f1b1e5c1aeb"
metafile = true

[[files]]
file = "mods/monsters-in-the-closet.pw.toml"
hash = "6afce08213c05a33240e980e2b92032a6a3ad25d2a54ff8e9f56b5f00d46d45d"
metafile = true

[[files]]
file = "mods/netherportalfix.pw.toml"
hash = "5dc059422613b5645cb00e32d3bfd53de428c4939113d11ce2c844cb54165da6"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "82a5c30ed91d272ee1895376e0d2cf57504b3d9db4aba6547e19eaa344861ada"
metafile = true

[[files]]
file = "mods/open-loader.pw.toml"
hash = "904c4adb3f8087a2c5381efd5d210183484934540372a5c839ab4790325e5cff"
metafile = true

[[files]]
file = "mods/particular-reforged.pw.toml"
hash = "527a5104f6d88a8c2603630d027c9a931a8bc6f61b46b4105082c150c1a812da"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
hash = "dee709ea8dbbb9e75de4d53b1b9e1fd0e535abc0809c1f5aaadf783178cccf21"
metafile = true

[[files]]
file = "mods/pretty-rain.pw.toml"
hash = "8319748b7c1a39462d159ed94da5c972b99958628c776be8d7c1e4c48fdaa5eb"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "a69a8ba0d9e52361b1853cf59b2cf2a38b668b1d508a565f315f2fa30407f546"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "09306b955060349986ccf6a6d2a67f1e019fa172a7dc690dd6007f81c966309a"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
hash = "f5476a132bfd78bfdc4335a62176da73da73190b639eac600f0ee3a9366ccbd9"
metafile = true

[[files]]
file = "mods/simpletms-tms-and-trs-for-cobblemon.pw.toml"
hash = "f8ba20a06c8391dedc25741ab2817e1af2bfb9a182eee248471dae4b41eb7d77"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "a1fb713df668ed21dda0602e99cb23b991c8faff841e130d7aae46258c3d6a45"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "02b29315d2ec0d055d0ebba1f36879da5bcacc823328a668c7e7340fb2cb03d4"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "d193173f0f5dfb4a921d44e29e8d5cee656dd3a40872939069715bb482b66fc9"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "c5687771065e4a43266b38018cbdf142b216916dd73aa6532b8282e3d0f06b9c"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "0281ed9713f3141bdac363056a791845510e14761ea65b4b2813cf96d664b20a"
metafile = true

[[files]]
file = "mods/sodiumleafculling.pw.toml"
hash = "a73dfb1bf6884ae786b2def0624dee9010bf121d0b5678b46043d9312f54b501"
metafile = true

[[files]]
file = "mods/swingthrough.pw.toml"
hash = "2f05b23513f7682101e2ab609964833f1b4e8557a3c9b272f7c51d9dfa7ad254"
metafile = true

[[files]]
file = "mods/tips.pw.toml"
hash = "ba47b8992285567792b0d79259d97e238ddea01702af50ab64a5316547039deb"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
hash = "2dda0b5d6b386fbbf9cf0deae33bdb4491b6aabda716a2d65040e4a730530473"
metafile = true

[[files]]
file = "mods/visuality-forge.pw.toml"
hash = "753745ebdd476d1b75252027f8cbbbba7334a71c49f9803652a53f5af111232c"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "6377c5bebeb5cda8b79689a2921ec8bd6cb2188b8e66c3e37c9c6ab03bf0d19f"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "639eeffde2132abdb13f5d9032a174c6e59feda680ac04a15c6962dfee9ab18a"
metafile = true
