name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "38ad37820608e7a706402122cee69c1efdd3094361cde391321a733ff1adc106"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
