name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffe514e3f9a4c98b7d8d6bb74fd120401bd8a2c6861278b507dbd1793ad32060"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
