name = "Cobblemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7b9debb849a14e74a8624e62e1268959b9f4435a59d039bddd0e5807615d7688"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
