name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feb849cc3ef8c24f3d9ab6ad99d3dcc7f09a5d5f1bae31349816d0f4935bf51e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
