name = "Cobblemon"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "379ed314842fb441dcb9789c750125c5c6251d4ed1d9451ad99b02fa59ae788b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
