name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64b10af33559c839123762a33a2ebfcfecbf9e6df255c04166be14056cb6a520"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
