name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "281fccc180ce15aaadea25f9738ebfec851ebed6d5f23307c5f02ab59b76177c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
