name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cce9b118dee7a5f4f3d899da4e39598dc6350e87c3f67eed59738c623135818e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
