name = "village pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "891f1addf53d66b897ed0b4519edb3a6c140f566b827617e6d126fe844e98b96"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
