name = "village pack"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d63fa5b80e10e6672ffc3d934a15b33afabab787d5d8708c8e93d01d5f4c932f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
