name = "poiesis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c1bce1fd65b3ea96a2255367afc6cd1414cdc2e1d57f60ccc4b50b63a7e2213"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.219"
